const actionTypes = {
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ADMIN_SUCCESS: "LOGIN_ADMIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGIN_ADMIN_FAIL: "LOGIN_ADMIN_FAIL",
    LOG_OUT_ADMIN: "LOG_OUT_ADMIN",
    CHANGE_PASS: "CHANGE_PASS",

    GET_ALL_RHS: "GET_ALL_RHS",
    GET_RHS: "GET_RHS",
    GET_RHS_LIMIT: "GET_RHS_LIMIT",
    GET_RHS_PUBLIC_BY_USER: "GET_RHS_PUBLIC_BY_USER",
    GET_RHS_BY_USER: "GET_RHS_BY_USER",
    GET_RHS_BY_USER_UNPAY: "GET_RHS_BY_USER_UNPAY",

    GET_TRANSACTION_TYPES: "GET_TRANSACTION_TYPES",
    GET_REAL_HOME_TYPES: "GET_REAL_HOME_TYPES",
    GET_REAL_HOME_TYPES_BY_TRANS: "GET_REAL_HOME_TYPES_BY_TRANS",

    // USER
    GET_All_LIMIT_USER: "GET_All_LIMIT_USER",
    GET_All_USER: "GET_All_USER",
    GET_USER: "GET_USER",
    GET_ADMIN: "GET_ADMIN",
    GET_SAVE_POST: "GET_SAVE_POST",
    GET_DETAIL_POST: "GET_DETAIL_POST",
    RH_EDIT: "RH_EDIT",
    DEL_DATA_EDIT: "DEL_DATA_EDIT",

    //PAYMENT
    GET_ALL_LIMIT_PAYMENT_HISTORY: "GET_ALL_LIMIT_PAYMENT_HISTORY",
    GET_ALL_PAYMENT_HISTORY: "GET_ALL_PAYMENT_HISTORY",
    GET_PAYMENT_HISTORY: "GET_PAYMENT_HISTORY",
    GET_NEWS_TYPE: "GET_NEWS_TYPE",

    // BLOG
    GET_ALL_LIMIT_BLOG: "GET_ALL_LIMIT_BLOG",
    BLOG_EDIT: "BLOG_EDIT",
    DEL_BLOG_EDIT: "DEL_BLOG_EDIT",
    GET_DETAIL_BLOG: "GET_DETAIL_BLOG",

    // BLOG TYPE
    GET_ALL_BLOG_TYPE: "GET_ALL_BLOG_TYPE",
};

export default actionTypes;
